version: '2.4'
services:

#========================================= INSERT_TO_DB ==========================================================

  insertion:
    image: ds_insert_to_db:cv2_added
    build:
      context: ./app
      dockerfile: ./dockerfiles/insertion/Dockerfile
    network_mode: "host"
    container_name: ds_insert_to_db_mobile
    depends_on:
      - kafka
    volumes:
      - ./app:/app/insert_to_db
      - /TENGRI/STORAGE/final_index:/final_index
      - ./configs/insert_to_db.conf:/app/insert_to_db.conf
      - /data_SDD/mobile_complex_test/aligned_images:/aligned_images
    working_dir: /app/insert_to_db
    restart: unless-stopped
    shm_size: 1g
    ulimits:
      memlock: -1
    #command: "tail -f /dev/null"
    command: sh -c "sleep 10s && python insert_to_db_mobile.py -c /app/insert_to_db.conf"
    environment:
      - PYTHONPATH=/root/faiss/build/faiss/python
      - ITD_PGSERVER_IP=10.202.100.16                           #Postgres server
      - ITD_PGSERVER_PORT=20005                                 #Postgres server port
      - ITD_PG_DB=fr_kpp                                        #Postgres database
      - ITD_PG_DB_USER=face_reco_admin                          #Postgres user
      - ITD_PG_DB_PASS=qwerty123                                #Postgres password
      - ITD_KAFKA_TOPIC=kpp_postgres                            #Kafka topic
      - ITD_KAFKA_SERVER=10.202.100.16                          #Kafka server
      - ITD_KAFKA_SERVER_PORT=40002                             #Kafka server port
      - ITD_KAFKA_OFFSET=earliest                               #Kafka offset policy. Consumption starts either at the earliest offset or the latest offset
      - ITD_KAFKA_AUTOCOMMIT=True                               #As the consumer reads messages from Kafka, it will periodically commit its current offset
      - ITD_KAFKA_GROUP=insert_to_db_1                          #Kafka group
      - ITD_FAISS_INDEX_FILE=/final_index/populated.index       #Faiss index file
      - ALIGNED_IMAGES_PATH=/aligned_images
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8

#========================================= KAFKA ==========================================================

  kafka:
    image: ds_kafka:latest
    # build: /data_SDD/kafka-docker/
    container_name: new_temp_kafka
    restart: unless-stopped
    ports:
      - "40002:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.202.100.16
      KAFKA_CREATE_TOPICS: "input:1:1,detection:1:1,recognition:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#========================================= ZOOKERPER ==========================================================

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: new_temp_zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
